// @ehrbase-ui/openehr-its-rest — openEHR ITS-REST 1.0.3 (the REST surface
// EHRbase 2.31.0 implements).
//
// Zod schemas generated by orval from the official openEHR ITS-REST OAS 3.0
// specs (vendored in ./openapi, pinned in ./openapi/.its-rest-commit). The BFF
// proxy (apps/web/src/server/bff/) is hand-written, so we generate validation
// schemas — not a fetch client — and validate responses crossing the network
// boundary (docs/architecture.md §15).
//
// Namespaced per API group to avoid cross-API name collisions. Regenerate with
// `pnpm --filter @ehrbase-ui/openehr-its-rest regen` (or `pnpm regen` for all).

export * as ehr from "./generated/ehr/ehrApi.ts";
export * as query from "./generated/query/queryAPI.ts";
export * as definition from "./generated/definition/definitionAPI.ts";
export { SPEC_COMPONENT, SPEC_VERSION } from "./spec.ts";
