/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiReadyRouteImport } from './routes/api/ready'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiCspReportRouteImport } from './routes/api/csp-report'
import { Route as AuthedMeRouteImport } from './routes/_authed/me'
import { Route as AuthedWorkbenchRouteRouteImport } from './routes/_authed/workbench/route'
import { Route as AuthedWorkbenchIndexRouteImport } from './routes/_authed/workbench/index'
import { Route as ApiLogClientErrorRouteImport } from './routes/api/log/client-error'
import { Route as ApiEhrbaseSplatRouteImport } from './routes/api/ehrbase/$'
import { Route as ApiDemographicSplatRouteImport } from './routes/api/demographic/$'
import { Route as ApiAuthBreakGlassRouteImport } from './routes/api/auth/break-glass'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedWorkbenchTemplatesRouteImport } from './routes/_authed/workbench/templates'
import { Route as AuthedWorkbenchEhrRouteImport } from './routes/_authed/workbench/ehr'
import { Route as AuthedWorkbenchAqlRouteImport } from './routes/_authed/workbench/aql'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReadyRoute = ApiReadyRouteImport.update({
  id: '/api/ready',
  path: '/api/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCspReportRoute = ApiCspReportRouteImport.update({
  id: '/api/csp-report',
  path: '/api/csp-report',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedMeRoute = AuthedMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedWorkbenchRouteRoute = AuthedWorkbenchRouteRouteImport.update({
  id: '/workbench',
  path: '/workbench',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedWorkbenchIndexRoute = AuthedWorkbenchIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedWorkbenchRouteRoute,
} as any)
const ApiLogClientErrorRoute = ApiLogClientErrorRouteImport.update({
  id: '/api/log/client-error',
  path: '/api/log/client-error',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEhrbaseSplatRoute = ApiEhrbaseSplatRouteImport.update({
  id: '/api/ehrbase/$',
  path: '/api/ehrbase/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDemographicSplatRoute = ApiDemographicSplatRouteImport.update({
  id: '/api/demographic/$',
  path: '/api/demographic/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthBreakGlassRoute = ApiAuthBreakGlassRouteImport.update({
  id: '/api/auth/break-glass',
  path: '/api/auth/break-glass',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedWorkbenchTemplatesRoute =
  AuthedWorkbenchTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => AuthedWorkbenchRouteRoute,
  } as any)
const AuthedWorkbenchEhrRoute = AuthedWorkbenchEhrRouteImport.update({
  id: '/ehr',
  path: '/ehr',
  getParentRoute: () => AuthedWorkbenchRouteRoute,
} as any)
const AuthedWorkbenchAqlRoute = AuthedWorkbenchAqlRouteImport.update({
  id: '/aql',
  path: '/aql',
  getParentRoute: () => AuthedWorkbenchRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/login': typeof LoginRoute
  '/workbench': typeof AuthedWorkbenchRouteRouteWithChildren
  '/me': typeof AuthedMeRoute
  '/api/csp-report': typeof ApiCspReportRoute
  '/api/health': typeof ApiHealthRoute
  '/api/ready': typeof ApiReadyRoute
  '/workbench/aql': typeof AuthedWorkbenchAqlRoute
  '/workbench/ehr': typeof AuthedWorkbenchEhrRoute
  '/workbench/templates': typeof AuthedWorkbenchTemplatesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/break-glass': typeof ApiAuthBreakGlassRoute
  '/api/demographic/$': typeof ApiDemographicSplatRoute
  '/api/ehrbase/$': typeof ApiEhrbaseSplatRoute
  '/api/log/client-error': typeof ApiLogClientErrorRoute
  '/workbench/': typeof AuthedWorkbenchIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/login': typeof LoginRoute
  '/me': typeof AuthedMeRoute
  '/api/csp-report': typeof ApiCspReportRoute
  '/api/health': typeof ApiHealthRoute
  '/api/ready': typeof ApiReadyRoute
  '/workbench/aql': typeof AuthedWorkbenchAqlRoute
  '/workbench/ehr': typeof AuthedWorkbenchEhrRoute
  '/workbench/templates': typeof AuthedWorkbenchTemplatesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/break-glass': typeof ApiAuthBreakGlassRoute
  '/api/demographic/$': typeof ApiDemographicSplatRoute
  '/api/ehrbase/$': typeof ApiEhrbaseSplatRoute
  '/api/log/client-error': typeof ApiLogClientErrorRoute
  '/workbench': typeof AuthedWorkbenchIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/accessibility': typeof AccessibilityRoute
  '/login': typeof LoginRoute
  '/_authed/workbench': typeof AuthedWorkbenchRouteRouteWithChildren
  '/_authed/me': typeof AuthedMeRoute
  '/api/csp-report': typeof ApiCspReportRoute
  '/api/health': typeof ApiHealthRoute
  '/api/ready': typeof ApiReadyRoute
  '/_authed/workbench/aql': typeof AuthedWorkbenchAqlRoute
  '/_authed/workbench/ehr': typeof AuthedWorkbenchEhrRoute
  '/_authed/workbench/templates': typeof AuthedWorkbenchTemplatesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/break-glass': typeof ApiAuthBreakGlassRoute
  '/api/demographic/$': typeof ApiDemographicSplatRoute
  '/api/ehrbase/$': typeof ApiEhrbaseSplatRoute
  '/api/log/client-error': typeof ApiLogClientErrorRoute
  '/_authed/workbench/': typeof AuthedWorkbenchIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accessibility'
    | '/login'
    | '/workbench'
    | '/me'
    | '/api/csp-report'
    | '/api/health'
    | '/api/ready'
    | '/workbench/aql'
    | '/workbench/ehr'
    | '/workbench/templates'
    | '/api/auth/$'
    | '/api/auth/break-glass'
    | '/api/demographic/$'
    | '/api/ehrbase/$'
    | '/api/log/client-error'
    | '/workbench/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accessibility'
    | '/login'
    | '/me'
    | '/api/csp-report'
    | '/api/health'
    | '/api/ready'
    | '/workbench/aql'
    | '/workbench/ehr'
    | '/workbench/templates'
    | '/api/auth/$'
    | '/api/auth/break-glass'
    | '/api/demographic/$'
    | '/api/ehrbase/$'
    | '/api/log/client-error'
    | '/workbench'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/accessibility'
    | '/login'
    | '/_authed/workbench'
    | '/_authed/me'
    | '/api/csp-report'
    | '/api/health'
    | '/api/ready'
    | '/_authed/workbench/aql'
    | '/_authed/workbench/ehr'
    | '/_authed/workbench/templates'
    | '/api/auth/$'
    | '/api/auth/break-glass'
    | '/api/demographic/$'
    | '/api/ehrbase/$'
    | '/api/log/client-error'
    | '/_authed/workbench/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  AccessibilityRoute: typeof AccessibilityRoute
  LoginRoute: typeof LoginRoute
  ApiCspReportRoute: typeof ApiCspReportRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiReadyRoute: typeof ApiReadyRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiAuthBreakGlassRoute: typeof ApiAuthBreakGlassRoute
  ApiDemographicSplatRoute: typeof ApiDemographicSplatRoute
  ApiEhrbaseSplatRoute: typeof ApiEhrbaseSplatRoute
  ApiLogClientErrorRoute: typeof ApiLogClientErrorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ready': {
      id: '/api/ready'
      path: '/api/ready'
      fullPath: '/api/ready'
      preLoaderRoute: typeof ApiReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/csp-report': {
      id: '/api/csp-report'
      path: '/api/csp-report'
      fullPath: '/api/csp-report'
      preLoaderRoute: typeof ApiCspReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/me': {
      id: '/_authed/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthedMeRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/workbench': {
      id: '/_authed/workbench'
      path: '/workbench'
      fullPath: '/workbench'
      preLoaderRoute: typeof AuthedWorkbenchRouteRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/workbench/': {
      id: '/_authed/workbench/'
      path: '/'
      fullPath: '/workbench/'
      preLoaderRoute: typeof AuthedWorkbenchIndexRouteImport
      parentRoute: typeof AuthedWorkbenchRouteRoute
    }
    '/api/log/client-error': {
      id: '/api/log/client-error'
      path: '/api/log/client-error'
      fullPath: '/api/log/client-error'
      preLoaderRoute: typeof ApiLogClientErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ehrbase/$': {
      id: '/api/ehrbase/$'
      path: '/api/ehrbase/$'
      fullPath: '/api/ehrbase/$'
      preLoaderRoute: typeof ApiEhrbaseSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/demographic/$': {
      id: '/api/demographic/$'
      path: '/api/demographic/$'
      fullPath: '/api/demographic/$'
      preLoaderRoute: typeof ApiDemographicSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/break-glass': {
      id: '/api/auth/break-glass'
      path: '/api/auth/break-glass'
      fullPath: '/api/auth/break-glass'
      preLoaderRoute: typeof ApiAuthBreakGlassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/workbench/templates': {
      id: '/_authed/workbench/templates'
      path: '/templates'
      fullPath: '/workbench/templates'
      preLoaderRoute: typeof AuthedWorkbenchTemplatesRouteImport
      parentRoute: typeof AuthedWorkbenchRouteRoute
    }
    '/_authed/workbench/ehr': {
      id: '/_authed/workbench/ehr'
      path: '/ehr'
      fullPath: '/workbench/ehr'
      preLoaderRoute: typeof AuthedWorkbenchEhrRouteImport
      parentRoute: typeof AuthedWorkbenchRouteRoute
    }
    '/_authed/workbench/aql': {
      id: '/_authed/workbench/aql'
      path: '/aql'
      fullPath: '/workbench/aql'
      preLoaderRoute: typeof AuthedWorkbenchAqlRouteImport
      parentRoute: typeof AuthedWorkbenchRouteRoute
    }
  }
}

interface AuthedWorkbenchRouteRouteChildren {
  AuthedWorkbenchAqlRoute: typeof AuthedWorkbenchAqlRoute
  AuthedWorkbenchEhrRoute: typeof AuthedWorkbenchEhrRoute
  AuthedWorkbenchTemplatesRoute: typeof AuthedWorkbenchTemplatesRoute
  AuthedWorkbenchIndexRoute: typeof AuthedWorkbenchIndexRoute
}

const AuthedWorkbenchRouteRouteChildren: AuthedWorkbenchRouteRouteChildren = {
  AuthedWorkbenchAqlRoute: AuthedWorkbenchAqlRoute,
  AuthedWorkbenchEhrRoute: AuthedWorkbenchEhrRoute,
  AuthedWorkbenchTemplatesRoute: AuthedWorkbenchTemplatesRoute,
  AuthedWorkbenchIndexRoute: AuthedWorkbenchIndexRoute,
}

const AuthedWorkbenchRouteRouteWithChildren =
  AuthedWorkbenchRouteRoute._addFileChildren(AuthedWorkbenchRouteRouteChildren)

interface AuthedRouteRouteChildren {
  AuthedWorkbenchRouteRoute: typeof AuthedWorkbenchRouteRouteWithChildren
  AuthedMeRoute: typeof AuthedMeRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedWorkbenchRouteRoute: AuthedWorkbenchRouteRouteWithChildren,
  AuthedMeRoute: AuthedMeRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  AccessibilityRoute: AccessibilityRoute,
  LoginRoute: LoginRoute,
  ApiCspReportRoute: ApiCspReportRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiReadyRoute: ApiReadyRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAuthBreakGlassRoute: ApiAuthBreakGlassRoute,
  ApiDemographicSplatRoute: ApiDemographicSplatRoute,
  ApiEhrbaseSplatRoute: ApiEhrbaseSplatRoute,
  ApiLogClientErrorRoute: ApiLogClientErrorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
