/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiReadyRouteImport } from './routes/api/ready'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiCspReportRouteImport } from './routes/api/csp-report'
import { Route as AuthedMeRouteImport } from './routes/_authed/me'
import { Route as ApiLogClientErrorRouteImport } from './routes/api/log/client-error'
import { Route as ApiEhrbaseSplatRouteImport } from './routes/api/ehrbase/$'
import { Route as ApiAuthBreakGlassRouteImport } from './routes/api/auth/break-glass'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedMeAccessLogRouteImport } from './routes/_authed/me_.access-log'
import { Route as ApiAdminAuditTasksSplatRouteImport } from './routes/api/admin/audit/tasks/$'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReadyRoute = ApiReadyRouteImport.update({
  id: '/api/ready',
  path: '/api/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCspReportRoute = ApiCspReportRouteImport.update({
  id: '/api/csp-report',
  path: '/api/csp-report',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedMeRoute = AuthedMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const ApiLogClientErrorRoute = ApiLogClientErrorRouteImport.update({
  id: '/api/log/client-error',
  path: '/api/log/client-error',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEhrbaseSplatRoute = ApiEhrbaseSplatRouteImport.update({
  id: '/api/ehrbase/$',
  path: '/api/ehrbase/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthBreakGlassRoute = ApiAuthBreakGlassRouteImport.update({
  id: '/api/auth/break-glass',
  path: '/api/auth/break-glass',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedMeAccessLogRoute = AuthedMeAccessLogRouteImport.update({
  id: '/me_/access-log',
  path: '/me/access-log',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const ApiAdminAuditTasksSplatRoute = ApiAdminAuditTasksSplatRouteImport.update({
  id: '/api/admin/audit/tasks/$',
  path: '/api/admin/audit/tasks/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/login': typeof LoginRoute
  '/me': typeof AuthedMeRoute
  '/api/csp-report': typeof ApiCspReportRoute
  '/api/health': typeof ApiHealthRoute
  '/api/ready': typeof ApiReadyRoute
  '/me/access-log': typeof AuthedMeAccessLogRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/break-glass': typeof ApiAuthBreakGlassRoute
  '/api/ehrbase/$': typeof ApiEhrbaseSplatRoute
  '/api/log/client-error': typeof ApiLogClientErrorRoute
  '/api/admin/audit/tasks/$': typeof ApiAdminAuditTasksSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/login': typeof LoginRoute
  '/me': typeof AuthedMeRoute
  '/api/csp-report': typeof ApiCspReportRoute
  '/api/health': typeof ApiHealthRoute
  '/api/ready': typeof ApiReadyRoute
  '/me/access-log': typeof AuthedMeAccessLogRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/break-glass': typeof ApiAuthBreakGlassRoute
  '/api/ehrbase/$': typeof ApiEhrbaseSplatRoute
  '/api/log/client-error': typeof ApiLogClientErrorRoute
  '/api/admin/audit/tasks/$': typeof ApiAdminAuditTasksSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/accessibility': typeof AccessibilityRoute
  '/login': typeof LoginRoute
  '/_authed/me': typeof AuthedMeRoute
  '/api/csp-report': typeof ApiCspReportRoute
  '/api/health': typeof ApiHealthRoute
  '/api/ready': typeof ApiReadyRoute
  '/_authed/me_/access-log': typeof AuthedMeAccessLogRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/break-glass': typeof ApiAuthBreakGlassRoute
  '/api/ehrbase/$': typeof ApiEhrbaseSplatRoute
  '/api/log/client-error': typeof ApiLogClientErrorRoute
  '/api/admin/audit/tasks/$': typeof ApiAdminAuditTasksSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accessibility'
    | '/login'
    | '/me'
    | '/api/csp-report'
    | '/api/health'
    | '/api/ready'
    | '/me/access-log'
    | '/api/auth/$'
    | '/api/auth/break-glass'
    | '/api/ehrbase/$'
    | '/api/log/client-error'
    | '/api/admin/audit/tasks/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accessibility'
    | '/login'
    | '/me'
    | '/api/csp-report'
    | '/api/health'
    | '/api/ready'
    | '/me/access-log'
    | '/api/auth/$'
    | '/api/auth/break-glass'
    | '/api/ehrbase/$'
    | '/api/log/client-error'
    | '/api/admin/audit/tasks/$'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/accessibility'
    | '/login'
    | '/_authed/me'
    | '/api/csp-report'
    | '/api/health'
    | '/api/ready'
    | '/_authed/me_/access-log'
    | '/api/auth/$'
    | '/api/auth/break-glass'
    | '/api/ehrbase/$'
    | '/api/log/client-error'
    | '/api/admin/audit/tasks/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  AccessibilityRoute: typeof AccessibilityRoute
  LoginRoute: typeof LoginRoute
  ApiCspReportRoute: typeof ApiCspReportRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiReadyRoute: typeof ApiReadyRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiAuthBreakGlassRoute: typeof ApiAuthBreakGlassRoute
  ApiEhrbaseSplatRoute: typeof ApiEhrbaseSplatRoute
  ApiLogClientErrorRoute: typeof ApiLogClientErrorRoute
  ApiAdminAuditTasksSplatRoute: typeof ApiAdminAuditTasksSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ready': {
      id: '/api/ready'
      path: '/api/ready'
      fullPath: '/api/ready'
      preLoaderRoute: typeof ApiReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/csp-report': {
      id: '/api/csp-report'
      path: '/api/csp-report'
      fullPath: '/api/csp-report'
      preLoaderRoute: typeof ApiCspReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/me': {
      id: '/_authed/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthedMeRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/api/log/client-error': {
      id: '/api/log/client-error'
      path: '/api/log/client-error'
      fullPath: '/api/log/client-error'
      preLoaderRoute: typeof ApiLogClientErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ehrbase/$': {
      id: '/api/ehrbase/$'
      path: '/api/ehrbase/$'
      fullPath: '/api/ehrbase/$'
      preLoaderRoute: typeof ApiEhrbaseSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/break-glass': {
      id: '/api/auth/break-glass'
      path: '/api/auth/break-glass'
      fullPath: '/api/auth/break-glass'
      preLoaderRoute: typeof ApiAuthBreakGlassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/me_/access-log': {
      id: '/_authed/me_/access-log'
      path: '/me/access-log'
      fullPath: '/me/access-log'
      preLoaderRoute: typeof AuthedMeAccessLogRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/api/admin/audit/tasks/$': {
      id: '/api/admin/audit/tasks/$'
      path: '/api/admin/audit/tasks/$'
      fullPath: '/api/admin/audit/tasks/$'
      preLoaderRoute: typeof ApiAdminAuditTasksSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedRouteRouteChildren {
  AuthedMeRoute: typeof AuthedMeRoute
  AuthedMeAccessLogRoute: typeof AuthedMeAccessLogRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedMeRoute: AuthedMeRoute,
  AuthedMeAccessLogRoute: AuthedMeAccessLogRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  AccessibilityRoute: AccessibilityRoute,
  LoginRoute: LoginRoute,
  ApiCspReportRoute: ApiCspReportRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiReadyRoute: ApiReadyRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAuthBreakGlassRoute: ApiAuthBreakGlassRoute,
  ApiEhrbaseSplatRoute: ApiEhrbaseSplatRoute,
  ApiLogClientErrorRoute: ApiLogClientErrorRoute,
  ApiAdminAuditTasksSplatRoute: ApiAdminAuditTasksSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
