// @ts-check
//
// ESLint v10 flat config.
//
// Plugin selection rationale lives in docs/architecture.md §12.3. The short
// version:
//
// - `eslint-plugin-jsx-a11y-x` is the actively-maintained fork of
//   `eslint-plugin-jsx-a11y` (canonical not ESLint-10-compatible yet).
//   Its rules carry the prefix `jsx-a11y-x/*` — the plugin must be aliased
//   under that exact name in the config.
// - `@eslint-react/eslint-plugin` is the modern rewrite of
//   `eslint-plugin-react` (canonical broken on ESLint 10, PR #3979 stalled).
// - `eslint-plugin-react-hooks@7` is the first major with native ESLint 10
//   support.
// - `typescript-eslint@8` officially supports `eslint ^8.57 || ^9 || ^10`.

import { defineConfig, globalIgnores } from 'eslint/config'
import js from '@eslint/js'
import tseslint from 'typescript-eslint'
import reactHooks from 'eslint-plugin-react-hooks'
import jsxA11yX from 'eslint-plugin-jsx-a11y-x'
import reactX from '@eslint-react/eslint-plugin'
import globals from 'globals'

export default defineConfig([
  globalIgnores([
    'node_modules/**',
    '**/node_modules/**',
    '**/.output/**',
    '**/.nitro/**',
    '**/dist/**',
    '**/build/**',
    '**/coverage/**',
    '**/playwright-report/**',
    '**/storybook-static/**',
    // Paraglide compiled output (regenerated by `pnpm paraglide:compile`).
    // Per ADR-0030 it lives in packages/i18n/src/paraglide/ now.
    'packages/i18n/src/paraglide/**',
    // Generated openEHR type code (regenerated by `pnpm regen` / `pnpm api:gen`):
    // the orval EHRbase REST client + the json-schema-to-zod output for every
    // openehr-* package (ADR-0032). Not hand-maintained; tsc still typechecks them.
    'packages/*/src/generated/**',
    // TanStack Router generated route tree.
    'apps/web/src/routeTree.gen.ts',
    'apps/web/.storybook/**',
    // Vendored shadcn/ui primitives — copied verbatim via the shadcn CLI
    // (docs/architecture.md §6) and not our code to maintain. Excluded from
    // ESLint entirely (and from Prettier, see .prettierignore) so a routine
    // `shadcn add` doesn't fail the strict src/** rules. tsc still typechecks
    // them — they remain type-valid. Live in apps/web/src/components/ui/.
    'apps/web/src/components/ui/**',
    'apps/web/src/hooks/use-mobile.ts',
    // Workspace package generated outputs / vendored content can extend the
    // ignore list here when packages start owning code (Phase 0 + later).
    'packages/*/dist/**',
    'packages/*/.tsbuildinfo',
  ]),

  // ───────────────────────────────────────────────────────────────────────
  // Source code (apps/web/src/, apps/web/e2e/, packages/*/src/) — TS, with
  // type information.
  // ───────────────────────────────────────────────────────────────────────
  {
    files: [
      'apps/web/src/**/*.{ts,tsx}',
      'apps/web/e2e/**/*.ts',
      'packages/*/src/**/*.{ts,tsx}',
    ],
    extends: [
      js.configs.recommended,
      tseslint.configs.recommendedTypeChecked,
    ],
    languageOptions: {
      ecmaVersion: 2024,
      sourceType: 'module',
      globals: {
        ...globals.browser,
        ...globals.node,
      },
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    plugins: {
      '@eslint-react': reactX,
      'react-hooks': reactHooks,
      'jsx-a11y-x': jsxA11yX,
    },
    rules: {
      ...reactX.configs.recommended.rules,

      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'error',

      ...jsxA11yX.configs.strict.rules,
      'jsx-a11y-x/alt-text': 'error',
      'jsx-a11y-x/anchor-has-content': 'error',
      // TanStack Router's <Link> renders a real <a> but uses `to` instead of
      // `href`; tell the rule that `to` is a valid navigable destination so
      // router links aren't flagged as empty anchors.
      'jsx-a11y-x/anchor-is-valid': ['error', { specialLink: ['to'] }],
      'jsx-a11y-x/aria-props': 'error',
      'jsx-a11y-x/aria-proptypes': 'error',
      'jsx-a11y-x/aria-role': 'error',
      'jsx-a11y-x/aria-unsupported-elements': 'error',
      'jsx-a11y-x/role-has-required-aria-props': 'error',
      'jsx-a11y-x/role-supports-aria-props': 'error',
      'jsx-a11y-x/label-has-associated-control': 'error',
      'jsx-a11y-x/no-redundant-roles': 'error',
      'jsx-a11y-x/click-events-have-key-events': 'error',
      'jsx-a11y-x/no-static-element-interactions': 'error',
      'jsx-a11y-x/no-noninteractive-element-interactions': 'error',
      'jsx-a11y-x/heading-has-content': 'error',
      'jsx-a11y-x/iframe-has-title': 'error',
      'jsx-a11y-x/img-redundant-alt': 'error',
      'jsx-a11y-x/no-autofocus': 'error',
      'jsx-a11y-x/no-distracting-elements': 'error',
      'jsx-a11y-x/scope': 'error',
      'jsx-a11y-x/tabindex-no-positive': 'error',
      'jsx-a11y-x/lang': 'error',
      'jsx-a11y-x/html-has-lang': 'error',
      'jsx-a11y-x/no-access-key': 'error',
      'jsx-a11y-x/media-has-caption': 'error',
      'jsx-a11y-x/no-aria-hidden-on-focusable': 'error',
      'jsx-a11y-x/prefer-tag-over-role': 'error',

      // No `as` casts — use Zod parse or type guards (docs/architecture.md §17).
      '@typescript-eslint/consistent-type-assertions': [
        'error',
        { assertionStyle: 'never' },
      ],

      // No third-party openEHR SDK on the dependency graph (ADR-0032). Our
      // openEHR types are generated from openEHR/specifications-ITS-JSON into
      // @ehrbase-ui/openehr-* — these abandoned/experimental libraries fail the
      // production-defensible-provenance bar.
      '@typescript-eslint/no-restricted-imports': [
        'error',
        {
          paths: [
            'ehrtslib',
            'medblocks-ui',
            '@bpac/openehr-models',
            '@mmt_d/mmt-openehr-types',
          ].map((name) => ({
            name,
            message:
              'No third-party openEHR SDK (ADR-0032). Use @ehrbase-ui/openehr-* generated from specifications-ITS-JSON.',
          })),
          patterns: [
            {
              group: [
                'ehrtslib/*',
                'medblocks-ui/*',
                '@bpac/openehr-models/*',
                '@mmt_d/mmt-openehr-types/*',
              ],
              message:
                'No third-party openEHR SDK (ADR-0032). Use @ehrbase-ui/openehr-* generated from specifications-ITS-JSON.',
            },
          ],
        },
      ],

      // Allow Promise-returning event handlers (React 19 form-action patterns).
      '@typescript-eslint/no-misused-promises': [
        'error',
        { checksVoidReturn: { attributes: false } },
      ],

      // The BFF pattern (docs/architecture.md §10) deliberately throws Response
      // objects to short-circuit with a structured { code, correlationId }
      // body, and TanStack's redirect() returns `Response & {…}` which is also
      // thrown. Both are intentional control flow, not error misuse.
      '@typescript-eslint/only-throw-error': [
        'error',
        {
          allow: [
            { from: 'lib', name: 'Response' },
            { from: 'package', package: '@tanstack/router-core', name: 'Redirect' },
          ],
        },
      ],
    },
    settings: {
      'jsx-a11y-x': {
        polymorphicPropName: 'as',
        components: {
          Button: 'button',
          Link: 'a',
          Image: 'img',
          Input: 'input',
          Label: 'label',
          Textarea: 'textarea',
        },
      },
    },
  },

  // ───────────────────────────────────────────────────────────────────────
  // Tests can use any-type assertions.
  // ───────────────────────────────────────────────────────────────────────
  {
    files: ['**/*.test.{ts,tsx}', '**/__tests__/**/*.{ts,tsx}', 'apps/web/e2e/**/*.ts'],
    rules: {
      '@typescript-eslint/consistent-type-assertions': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
      // Test doubles emulate libraries that throw/reject with non-Error values
      // (e.g. rate-limiter-flexible rejects with a RateLimiterRes).
      '@typescript-eslint/only-throw-error': 'off',
      '@typescript-eslint/prefer-promise-reject-errors': 'off',
    },
  },

  // ───────────────────────────────────────────────────────────────────────
  // Root config / build scripts — JS, no type information available.
  // ───────────────────────────────────────────────────────────────────────
  {
    files: ['*.{ts,js,mjs,cjs}'],
    extends: [
      js.configs.recommended,
      tseslint.configs.disableTypeChecked,
    ],
    languageOptions: {
      globals: { ...globals.node },
    },
    rules: {
      // Root TS configs (vite.config.ts, vitest.config.ts) are not inside the
      // project tsconfig — we skip type-aware rules here.
      '@typescript-eslint/no-explicit-any': 'off',
    },
  },
])
