// Shared openEHR type-generation pipeline (ADR-0032 + 2026-05-30 addendum).
//
// Reusable across every generated openehr-* package. Run from a package
// directory (pnpm --filter <pkg> regen); it reads ./spec.json + ./schema/**
// and emits ./src/generated/<specVersion>/index.ts + ./src/generated/current.ts.
//
//   node ../../scripts/openehr-codegen.mjs          # regenerate (write)
//   node ../../scripts/openehr-codegen.mjs --check   # CI drift gate (no write; exit 1 on diff)
//
// The vendored ./schema/ files are the offline source of truth (provenance =
// the commit pinned in spec.json). Refresh them with `regen:fetch` (online).
// Generation is fully deterministic so `--check` is stable in CI.
//
// Cross-file $refs in the ITS-JSON schemas are absolute URLs ending in
// `<File>.json#/definitions/<NAME>`; we rewrite them to local `#/definitions/<NAME>`
// so json-schema-to-zod can resolve them. Polymorphic id fields (OBJECT_REF /
// LOCATABLE_REF / PARTY_REF) generate as `z.intersection(z.any())` — that is
// expected; the hand-written facade replaces them with proper discriminated
// unions. Consumers import the facade (package root), never src/generated/*.

import fs from "node:fs";
import path from "node:path";
import { jsonSchemaToZod } from "json-schema-to-zod";

const checkMode = process.argv.includes("--check");
const pkgDir = process.cwd();

const specPath = path.join(pkgDir, "spec.json");
if (!fs.existsSync(specPath)) {
  console.error(`[openehr-codegen] no spec.json in ${pkgDir}`);
  process.exit(1);
}
const spec = JSON.parse(fs.readFileSync(specPath, "utf8"));
const schemaDir = path.join(pkgDir, "schema");

/** Recursively collect every *.json schema file under ./schema. */
function collectSchemaFiles(dir) {
  const out = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...collectSchemaFiles(full));
    else if (entry.name.endsWith(".json")) out.push(full);
  }
  return out;
}

/** Rewrite absolute ITS-JSON $refs to local `#/definitions/<NAME>`. */
function localiseRefs(node) {
  return JSON.parse(
    JSON.stringify(node).replace(
      /"\$ref":"[^"]*#\/definitions\/([A-Za-z0-9_]+)"/g,
      '"$ref":"#/definitions/$1"',
    ),
  );
}

const defs = {};
for (const file of collectSchemaFiles(schemaDir)) {
  const json = JSON.parse(fs.readFileSync(file, "utf8"));
  for (const [name, def] of Object.entries(json.definitions ?? {})) {
    defs[name] = def;
  }
}
const allDefs = localiseRefs(defs);
const classNames = Object.keys(allDefs).sort();

const banner =
  `// AUTOGENERATED — do not edit by hand.\n` +
  `// Run \`pnpm regen\` after editing spec.json (refresh schema/ first with \`pnpm regen:fetch\`).\n` +
  `// Source: ${spec.schemaSource} ${spec.schemaRef} @ ${spec.schemaCommit}\n` +
  `// openEHR ${spec.component} ${spec.specVersion} — ${classNames.length} classes. See ADR-0032.\n` +
  `/* eslint-disable */\n`;

let body = `${banner}import { z } from "zod";\n`;
for (const cls of classNames) {
  const schema = { ...allDefs[cls], definitions: allDefs };
  const code = jsonSchemaToZod(schema, { name: cls, module: "esm", type: false })
    .replace(/^import .*$\n/m, "")
    .trim();
  body += `${code}\n`;
}

const genDir = path.join(pkgDir, "src", "generated", spec.specVersion);
const genFile = path.join(genDir, "index.ts");
const currentFile = path.join(pkgDir, "src", "generated", "current.ts");
const currentBody =
  `// AUTOGENERATED — do not edit by hand. Run \`pnpm regen\`.\n` +
  `// Re-exports the active openEHR ${spec.component} ${spec.specVersion} generated types.\n` +
  `/* eslint-disable */\n` +
  `export * from "./${spec.specVersion}/index.ts";\n`;

if (checkMode) {
  const existing = fs.existsSync(genFile) ? fs.readFileSync(genFile, "utf8") : "";
  const existingCurrent = fs.existsSync(currentFile)
    ? fs.readFileSync(currentFile, "utf8")
    : "";
  if (existing !== body || existingCurrent !== currentBody) {
    console.error(
      `[openehr-codegen] DRIFT in ${spec.component} ${spec.specVersion}: generated output differs from committed. Run \`pnpm regen\`.`,
    );
    process.exit(1);
  }
  console.log(`[openehr-codegen] ${spec.component} ${spec.specVersion} up to date (${classNames.length} classes).`);
} else {
  fs.mkdirSync(genDir, { recursive: true });
  fs.writeFileSync(genFile, body);
  fs.writeFileSync(currentFile, currentBody);
  console.log(`[openehr-codegen] wrote ${classNames.length} classes → ${path.relative(pkgDir, genFile)}`);
}
