// openEHR FieldRenderer — recursive, rmType-aware form field renderer.
//
// Anchored in: docs/architecture.md §7 (form pipeline).
// rmType → shadcn component mapping per §7 table.
//
// CONTRACT: the form-state shape this renderer reads/writes MUST match exactly
// what `generateFormSchema(template)` validates AND what `formStateToFlat`
// consumes. Both are the authoritative source of truth. This renderer derives
// its structure from the WebTemplateNode tree — it never invents a new
// form-state shape.
//
// Validation comes from the Zod schema generated by generateFormSchema (via
// zodResolver in ComposeForm). No hand-written validation rules live here
// (Inviolable rule 1 for the form pipeline).

import { useState } from 'react'
import {
  type Control,
  type FieldValues,
  Controller,
  type FieldError,
  useFieldArray,
  useFormContext,
} from 'react-hook-form'

import type { WebTemplateNode } from '@ehrbase-ui/openehr-web-template'
import { m } from '@ehrbase-ui/i18n/messages'

import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { Switch } from '@/components/ui/switch'
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group'
import { Label } from '@/components/ui/label'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover'
import { Calendar } from '@/components/ui/calendar'
import { Button } from '@/components/ui/button'
import { cn } from '@/lib/utils'

// ── Container rmTypes ─────────────────────────────────────────────────────────
// These nodes recurse into children; they are never leaf inputs themselves.
const CONTAINER_RM_TYPES = new Set([
  'COMPOSITION',
  'SECTION',
  'CLUSTER',
  'ITEM_TREE',
  'ITEM_LIST',
  'ITEM_SINGLE',
  'ITEM_TABLE',
  'HISTORY',
  'EVENT',
  'POINT_EVENT',
  'INTERVAL_EVENT',
  'EVENT_CONTEXT',
  'ADMIN_ENTRY',
  'OBSERVATION',
  'EVALUATION',
  'INSTRUCTION',
  'ACTION',
  'ELEMENT',
])

// Helper: resolve the localized display name for a node.
function nodeName(node: WebTemplateNode): string {
  return (
    node.localizedNames?.['en'] ??
    node.localizedName ??
    node.name ??
    node.id
  )
}

// Helper: does the node have no inputs AND is in the container set?
function isContainer(node: WebTemplateNode): boolean {
  const hasInputs = (node.inputs?.length ?? 0) > 0
  return !hasInputs && CONTAINER_RM_TYPES.has(node.rmType)
}

// Helper: max-length heuristic for DV_TEXT → Textarea vs Input.
// The §7 table says: textarea if maxLength > 80. We use the validation range
// max as a proxy; if unconstrained, default to Textarea (clinical notes).
function isLongText(node: WebTemplateNode): boolean {
  const inp = node.inputs?.[0]
  const maxLen = inp?.validation?.range?.max
  if (typeof maxLen === 'number') return maxLen > 80
  return true
}

// Helper: extract an error message from an RHF FieldError.
function errorMessage(error: FieldError | undefined): string | undefined {
  if (!error) return undefined
  return error.message ?? 'Invalid value'
}

// Helper: type guard for composite form-state leaf records (DV_QUANTITY etc.).
function isCompositeRecord(x: unknown): x is Record<string, unknown> {
  return typeof x === 'object' && x !== null && !Array.isArray(x)
}

// ── Required marker ───────────────────────────────────────────────────────────
function RequiredMark() {
  return (
    <span className="text-destructive ml-1" aria-label={m.compose_required_label()}>
      {m.compose_required_marker()}
    </span>
  )
}

// ── Read-only static value display ───────────────────────────────────────────
// When readOnly=true, leaf values are rendered as labelled static text instead
// of interactive inputs. This is the display mode used by CompositionViewer.

interface ReadOnlyLeafProps {
  label: string
  value: string
}

function ReadOnlyField({ label, value }: ReadOnlyLeafProps) {
  return (
    <div className="flex flex-col gap-0.5">
      <span className="text-muted-foreground text-xs font-medium">{label}</span>
      <span className="text-sm">{value || m.compose_value_empty()}</span>
    </div>
  )
}

// ── Leaf renderers ────────────────────────────────────────────────────────────

interface LeafProps {
  node: WebTemplateNode
  path: string
  control: Control<Record<string, unknown>>
  readOnly?: boolean
}

// DV_TEXT → Input (short) / Textarea (long). §7 table row 1.
function DvTextField({ node, path, control, readOnly }: LeafProps) {
  const required = (node.min ?? 0) >= 1
  const long = isLongText(node)
  const label = nodeName(node)
  const inputId = `field-${path}`

  return (
    <Controller
      control={control}
      name={path}
      render={({ field, fieldState }) => {
        const val = typeof field.value === 'string' ? field.value : ''
        const err = errorMessage(fieldState.error)
        if (readOnly) return <ReadOnlyField label={label} value={val} />
        return (
          <div className="flex flex-col gap-1">
            <Label htmlFor={inputId}>
              {label}
              {required && <RequiredMark />}
            </Label>
            {long ? (
              <Textarea
                id={inputId}
                value={val}
                onChange={(e) => field.onChange(e.target.value)}
                onBlur={field.onBlur}
                aria-invalid={fieldState.invalid}
                aria-describedby={err ? `${inputId}-err` : undefined}
              />
            ) : (
              <Input
                id={inputId}
                type="text"
                value={val}
                onChange={(e) => field.onChange(e.target.value)}
                onBlur={field.onBlur}
                aria-invalid={fieldState.invalid}
                aria-describedby={err ? `${inputId}-err` : undefined}
              />
            )}
            {err && (
              <p id={`${inputId}-err`} role="alert" className="text-destructive text-xs">
                {err}
              </p>
            )}
          </div>
        )
      }}
    />
  )
}

// DV_CODED_TEXT → Select (≤7 options) / Combobox (>7 or open list). §7 table row 2.
// Form-state shape: `{ code: string }` when a code suffix exists; scalar string
// for single suffix-less input — matching leafSchema() in generate-form-schema.ts.
function DvCodedTextField({ node, path, control, readOnly }: LeafProps) {
  const required = (node.min ?? 0) >= 1
  const label = nodeName(node)
  const inputs = node.inputs ?? []
  const codeInput = inputs.find((i) => i.suffix === 'code') ?? inputs[0]
  const list = codeInput?.list ?? []
  const isClosedList = list.length > 0 && !codeInput?.listOpen
  const isSmall = isClosedList && list.length <= 7
  const hasCodeSuffix = !!inputs.find((i) => i.suffix === 'code')
  const fieldPath = hasCodeSuffix ? `${path}.code` : path
  const inputId = `field-${fieldPath}`

  return (
    <Controller
      control={control}
      name={fieldPath}
      render={({ field, fieldState }) => {
        const val = typeof field.value === 'string' ? field.value : ''
        const err = errorMessage(fieldState.error)

        if (readOnly) {
          // Resolve the display label for the current code value.
          const displayLabel = list.find((i) => i.value === val)
            ?.localizedLabels?.['en'] ?? list.find((i) => i.value === val)?.label ?? val
          return <ReadOnlyField label={label} value={displayLabel} />
        }

        if (isSmall) {
          return (
            <div className="flex flex-col gap-1">
              <Label htmlFor={inputId}>
                {label}
                {required && <RequiredMark />}
              </Label>
              <Select value={val} onValueChange={(v) => field.onChange(v)}>
                <SelectTrigger id={inputId} aria-invalid={fieldState.invalid}>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {list.map((item) => (
                    <SelectItem key={item.value} value={item.value}>
                      {item.localizedLabels?.['en'] ?? item.label ?? item.value}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
              {err && (
                <p id={`${inputId}-err`} role="alert" className="text-destructive text-xs">
                  {err}
                </p>
              )}
            </div>
          )
        }

        // Large or open list: Input with datalist (combobox pattern).
        return (
          <div className="flex flex-col gap-1">
            <Label htmlFor={inputId}>
              {label}
              {required && <RequiredMark />}
            </Label>
            <Input
              id={inputId}
              type="text"
              value={val}
              onChange={(e) => field.onChange(e.target.value)}
              onBlur={field.onBlur}
              aria-invalid={fieldState.invalid}
              aria-describedby={err ? `${inputId}-err` : undefined}
              list={list.length > 0 ? `${inputId}-list` : undefined}
            />
            {list.length > 0 && (
              <datalist id={`${inputId}-list`}>
                {list.map((item) => (
                  <option key={item.value} value={item.value}>
                    {item.localizedLabels?.['en'] ?? item.label ?? item.value}
                  </option>
                ))}
              </datalist>
            )}
            {err && (
              <p id={`${inputId}-err`} role="alert" className="text-destructive text-xs">
                {err}
              </p>
            )}
          </div>
        )
      }}
    />
  )
}

// DV_QUANTITY → number Input + unit Select. §7 table row 3.
// Form-state shape: `{ magnitude: number, unit: string }` (composite leaf).
function DvQuantityField({ node, path, control, readOnly }: LeafProps) {
  const required = (node.min ?? 0) >= 1
  const label = nodeName(node)
  const inputs = node.inputs ?? []
  const magnitudeInput = inputs.find((i) => i.suffix === 'magnitude')
  const unitInput = inputs.find((i) => i.suffix === 'unit')
  const units = unitInput?.list ?? []
  const magId = `field-${path}.magnitude`
  const unitId = `field-${path}.unit`

  if (readOnly) {
    return (
      <Controller
        control={control}
        name={path}
        render={({ field }) => {
          const composite = field.value
          const raw = isCompositeRecord(composite) ? composite : {}
          const mag = typeof raw['magnitude'] === 'number' ? raw['magnitude'] : undefined
          const unit = typeof raw['unit'] === 'string' ? raw['unit'] : undefined
          const display = [mag !== undefined ? String(mag) : '', unit ?? '']
            .filter(Boolean)
            .join(' ')
          return <ReadOnlyField label={label} value={display} />
        }}
      />
    )
  }

  return (
    <fieldset className="flex flex-col gap-1">
      <legend className="text-sm font-medium leading-none">
        {label}
        {required && <RequiredMark />}
      </legend>
      <div className="flex gap-2">
        <Controller
          control={control}
          name={`${path}.magnitude`}
          render={({ field, fieldState }) => {
            const numVal = typeof field.value === 'number' ? field.value : ''
            const err = errorMessage(fieldState.error)
            const rangeMin = magnitudeInput?.validation?.range?.min
            const rangeMax = magnitudeInput?.validation?.range?.max
            return (
              <div className="flex flex-1 flex-col gap-1">
                <Label htmlFor={magId} className="sr-only">
                  {label} magnitude
                </Label>
                <Input
                  id={magId}
                  type="number"
                  value={numVal}
                  min={typeof rangeMin === 'number' ? rangeMin : undefined}
                  max={typeof rangeMax === 'number' ? rangeMax : undefined}
                  step="any"
                  onChange={(e) => {
                    const v = e.target.value
                    field.onChange(v === '' ? undefined : Number(v))
                  }}
                  onBlur={field.onBlur}
                  aria-invalid={fieldState.invalid}
                  aria-describedby={err ? `${magId}-err` : undefined}
                />
                {err && (
                  <p id={`${magId}-err`} role="alert" className="text-destructive text-xs">
                    {err}
                  </p>
                )}
              </div>
            )
          }}
        />
        {units.length > 0 && (
          <Controller
            control={control}
            name={`${path}.unit`}
            render={({ field, fieldState }) => {
              const val = typeof field.value === 'string' ? field.value : ''
              return (
                <div className="flex flex-col gap-1">
                  <Label htmlFor={unitId} className="sr-only">
                    {label} unit
                  </Label>
                  <Select value={val} onValueChange={(v) => field.onChange(v)}>
                    <SelectTrigger id={unitId} aria-invalid={fieldState.invalid}>
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      {units.map((u) => (
                        <SelectItem key={u.value} value={u.value}>
                          {u.localizedLabels?.['en'] ?? u.label ?? u.value}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
              )
            }}
          />
        )}
      </div>
    </fieldset>
  )
}

// DV_COUNT → number Input (integer step). §7 table row 4.
// Form-state shape: scalar number (single suffix-less INTEGER input).
function DvCountField({ node, path, control, readOnly }: LeafProps) {
  const required = (node.min ?? 0) >= 1
  const label = nodeName(node)
  const inputId = `field-${path}`
  const inp = node.inputs?.[0]
  const rangeMin = inp?.validation?.range?.min
  const rangeMax = inp?.validation?.range?.max

  return (
    <Controller
      control={control}
      name={path}
      render={({ field, fieldState }) => {
        const numVal = typeof field.value === 'number' ? field.value : ''
        const err = errorMessage(fieldState.error)
        if (readOnly) return <ReadOnlyField label={label} value={numVal !== '' ? String(numVal) : ''} />
        return (
          <div className="flex flex-col gap-1">
            <Label htmlFor={inputId}>
              {label}
              {required && <RequiredMark />}
            </Label>
            <Input
              id={inputId}
              type="number"
              step="1"
              value={numVal}
              min={typeof rangeMin === 'number' ? rangeMin : undefined}
              max={typeof rangeMax === 'number' ? rangeMax : undefined}
              onChange={(e) => {
                const v = e.target.value
                field.onChange(v === '' ? undefined : Number(v))
              }}
              onBlur={field.onBlur}
              aria-invalid={fieldState.invalid}
              aria-describedby={err ? `${inputId}-err` : undefined}
            />
            {err && (
              <p id={`${inputId}-err`} role="alert" className="text-destructive text-xs">
                {err}
              </p>
            )}
          </div>
        )
      }}
    />
  )
}

// DV_BOOLEAN → Switch with inline label. §7 table row 5.
// Form-state shape: scalar boolean.
function DvBooleanField({ node, path, control, readOnly }: LeafProps) {
  const required = (node.min ?? 0) >= 1
  const label = nodeName(node)
  const switchId = `field-${path}`

  return (
    <Controller
      control={control}
      name={path}
      render={({ field, fieldState }) => {
        const checked = field.value === true
        const err = errorMessage(fieldState.error)
        if (readOnly) return <ReadOnlyField label={label} value={checked ? 'Yes' : 'No'} />
        return (
          <div className="flex flex-col gap-1">
            <div className="flex items-center gap-2">
              <Switch
                id={switchId}
                checked={checked}
                onCheckedChange={(v) => field.onChange(v)}
                aria-invalid={fieldState.invalid}
              />
              <Label htmlFor={switchId}>
                {label}
                {required && <RequiredMark />}
              </Label>
            </div>
            {err && (
              <p role="alert" className="text-destructive text-xs">
                {err}
              </p>
            )}
          </div>
        )
      }}
    />
  )
}

// DV_DATE → Calendar + Popover. §7 table row 6.
// Form-state shape: ISO 8601 date string (bare FLAT key, no |suffix).
// useState is in the component body (not inside the render callback) per the Rules of Hooks.
function DvDateField({ node, path, control, readOnly }: LeafProps) {
  const required = (node.min ?? 0) >= 1
  const label = nodeName(node)
  const triggerId = `field-${path}`
  // Popover open state lives in the component body, not inside the render callback.
  const [open, setOpen] = useState(false)

  return (
    <Controller
      control={control}
      name={path}
      render={({ field, fieldState }) => {
        const strVal = typeof field.value === 'string' ? field.value : ''
        const dateVal = strVal ? new Date(strVal) : undefined
        const err = errorMessage(fieldState.error)

        if (readOnly) return <ReadOnlyField label={label} value={strVal} />

        return (
          <div className="flex flex-col gap-1">
            <Label htmlFor={triggerId}>
              {label}
              {required && <RequiredMark />}
            </Label>
            {/* aria-describedby on the trigger div conveys the invalid state.
                Buttons don't support aria-invalid (role-supports-aria-props). */}
            <div
              aria-describedby={err ? `${triggerId}-err` : undefined}
            >
              <Popover open={open} onOpenChange={setOpen}>
                <PopoverTrigger asChild>
                  <Button
                    id={triggerId}
                    variant="outline"
                    type="button"
                    className={cn(
                      'w-full justify-start text-left font-normal',
                      !strVal && 'text-muted-foreground',
                      fieldState.invalid && 'border-destructive',
                    )}
                  >
                    {strVal || label}
                  </Button>
                </PopoverTrigger>
                <PopoverContent className="w-auto p-0" align="start">
                  <Calendar
                    mode="single"
                    selected={dateVal}
                    onSelect={(d) => {
                      if (d) {
                        field.onChange(d.toISOString().slice(0, 10))
                      }
                      setOpen(false)
                    }}
                  />
                </PopoverContent>
              </Popover>
            </div>
            {err && (
              <p id={`${triggerId}-err`} role="alert" className="text-destructive text-xs">
                {err}
              </p>
            )}
          </div>
        )
      }}
    />
  )
}

// DV_DATE_TIME → datetime-local Input. §7 table row 6 (full datetime).
// Form-state shape: ISO 8601 datetime string (bare FLAT key, no |suffix).
function DvDateTimeField({ node, path, control, readOnly }: LeafProps) {
  const required = (node.min ?? 0) >= 1
  const label = nodeName(node)
  const inputId = `field-${path}`

  return (
    <Controller
      control={control}
      name={path}
      render={({ field, fieldState }) => {
        const strVal = typeof field.value === 'string' ? field.value : ''
        const err = errorMessage(fieldState.error)
        const localVal = strVal ? strVal.slice(0, 16) : ''
        if (readOnly) return <ReadOnlyField label={label} value={strVal} />
        return (
          <div className="flex flex-col gap-1">
            <Label htmlFor={inputId}>
              {label}
              {required && <RequiredMark />}
            </Label>
            <Input
              id={inputId}
              type="datetime-local"
              value={localVal}
              onChange={(e) => {
                field.onChange(e.target.value ? `${e.target.value}:00` : '')
              }}
              onBlur={field.onBlur}
              aria-invalid={fieldState.invalid}
              aria-describedby={err ? `${inputId}-err` : undefined}
            />
            {err && (
              <p id={`${inputId}-err`} role="alert" className="text-destructive text-xs">
                {err}
              </p>
            )}
          </div>
        )
      }}
    />
  )
}

// DV_TIME → time Input.
// Form-state shape: ISO 8601 time string (bare FLAT key, no |suffix).
function DvTimeField({ node, path, control, readOnly }: LeafProps) {
  const required = (node.min ?? 0) >= 1
  const label = nodeName(node)
  const inputId = `field-${path}`

  return (
    <Controller
      control={control}
      name={path}
      render={({ field, fieldState }) => {
        const strVal = typeof field.value === 'string' ? field.value : ''
        const err = errorMessage(fieldState.error)
        if (readOnly) return <ReadOnlyField label={label} value={strVal} />
        return (
          <div className="flex flex-col gap-1">
            <Label htmlFor={inputId}>
              {label}
              {required && <RequiredMark />}
            </Label>
            <Input
              id={inputId}
              type="time"
              value={strVal}
              onChange={(e) => field.onChange(e.target.value)}
              onBlur={field.onBlur}
              aria-invalid={fieldState.invalid}
              aria-describedby={err ? `${inputId}-err` : undefined}
            />
            {err && (
              <p id={`${inputId}-err`} role="alert" className="text-destructive text-xs">
                {err}
              </p>
            )}
          </div>
        )
      }}
    />
  )
}

// DV_ORDINAL → RadioGroup (≤7 options) / Select (>7). §7 table row 7.
// Form-state shape: mirrors DV_CODED_TEXT (code suffix → `{ code }`, else scalar).
function DvOrdinalField({ node, path, control, readOnly }: LeafProps) {
  const required = (node.min ?? 0) >= 1
  const label = nodeName(node)
  const inputs = node.inputs ?? []
  const codeInput = inputs.find((i) => i.suffix === 'code') ?? inputs[0]
  const list = codeInput?.list ?? []
  const isSmall = list.length <= 7
  const hasCodeSuffix = !!inputs.find((i) => i.suffix === 'code')
  const fieldPath = hasCodeSuffix ? `${path}.code` : path
  const groupId = `field-${fieldPath}`

  return (
    <Controller
      control={control}
      name={fieldPath}
      render={({ field, fieldState }) => {
        const val = typeof field.value === 'string' ? field.value : ''
        const err = errorMessage(fieldState.error)

        if (readOnly) {
          const displayLabel = list.find((i) => i.value === val)?.localizedLabels?.['en']
            ?? list.find((i) => i.value === val)?.label ?? val
          return <ReadOnlyField label={label} value={displayLabel} />
        }

        if (isSmall) {
          return (
            <fieldset className="flex flex-col gap-2">
              <legend className="text-sm font-medium leading-none">
                {label}
                {required && <RequiredMark />}
              </legend>
              <RadioGroup
                id={groupId}
                value={val}
                onValueChange={(v) => field.onChange(v)}
                aria-invalid={fieldState.invalid}
              >
                {list.map((item, idx) => {
                  const radioId = `${groupId}-${idx}`
                  const itemLabel =
                    item.localizedLabels?.['en'] ?? item.label ?? item.value
                  const ordinalDisplay =
                    typeof item.ordinal === 'number' ? `${item.ordinal}. ` : ''
                  return (
                    <div key={item.value} className="flex items-center gap-2">
                      <RadioGroupItem id={radioId} value={item.value} />
                      <Label htmlFor={radioId}>
                        {ordinalDisplay}
                        {itemLabel}
                      </Label>
                    </div>
                  )
                })}
              </RadioGroup>
              {err && (
                <p role="alert" className="text-destructive text-xs">
                  {err}
                </p>
              )}
            </fieldset>
          )
        }

        const selectId = `field-${fieldPath}-select`
        return (
          <div className="flex flex-col gap-1">
            <Label htmlFor={selectId}>
              {label}
              {required && <RequiredMark />}
            </Label>
            <Select value={val} onValueChange={(v) => field.onChange(v)}>
              <SelectTrigger id={selectId} aria-invalid={fieldState.invalid}>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {list.map((item) => (
                  <SelectItem key={item.value} value={item.value}>
                    {typeof item.ordinal === 'number' ? `${item.ordinal}. ` : ''}
                    {item.localizedLabels?.['en'] ?? item.label ?? item.value}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
            {err && (
              <p role="alert" className="text-destructive text-xs">
                {err}
              </p>
            )}
          </div>
        )
      }}
    />
  )
}

// DV_PROPORTION → two number Inputs + slash. §7 table row 8.
// Form-state shape: `{ numerator: number, denominator: number }`.
function DvProportionField({ node, path, control, readOnly }: LeafProps) {
  const required = (node.min ?? 0) >= 1
  const label = nodeName(node)
  const numId = `field-${path}.numerator`
  const denomId = `field-${path}.denominator`

  if (readOnly) {
    return (
      <Controller
        control={control}
        name={path}
        render={({ field }) => {
          const composite = field.value
          const raw = isCompositeRecord(composite) ? composite : {}
          const num = typeof raw['numerator'] === 'number' ? raw['numerator'] : undefined
          const denom = typeof raw['denominator'] === 'number' ? raw['denominator'] : undefined
          const display = [num !== undefined ? String(num) : '', denom !== undefined ? String(denom) : '']
            .filter(Boolean)
            .join(' / ')
          return <ReadOnlyField label={label} value={display} />
        }}
      />
    )
  }

  return (
    <fieldset className="flex flex-col gap-1">
      <legend className="text-sm font-medium leading-none">
        {label}
        {required && <RequiredMark />}
      </legend>
      <div className="flex items-center gap-2">
        <Controller
          control={control}
          name={`${path}.numerator`}
          render={({ field, fieldState }) => (
            <div className="flex flex-col gap-1">
              <Label htmlFor={numId} className="sr-only">
                Numerator
              </Label>
              <Input
                id={numId}
                type="number"
                step="any"
                value={typeof field.value === 'number' ? field.value : ''}
                onChange={(e) => {
                  field.onChange(e.target.value === '' ? undefined : Number(e.target.value))
                }}
                onBlur={field.onBlur}
                aria-invalid={fieldState.invalid}
                className="w-24"
              />
            </div>
          )}
        />
        <span aria-hidden="true" className="text-muted-foreground">
          /
        </span>
        <Controller
          control={control}
          name={`${path}.denominator`}
          render={({ field, fieldState }) => (
            <div className="flex flex-col gap-1">
              <Label htmlFor={denomId} className="sr-only">
                Denominator
              </Label>
              <Input
                id={denomId}
                type="number"
                step="any"
                value={typeof field.value === 'number' ? field.value : ''}
                onChange={(e) => {
                  field.onChange(e.target.value === '' ? undefined : Number(e.target.value))
                }}
                onBlur={field.onBlur}
                aria-invalid={fieldState.invalid}
                className="w-24"
              />
            </div>
          )}
        />
      </div>
    </fieldset>
  )
}

// DV_DURATION → text Input (ISO 8601 duration string, e.g. "P1Y2M3DT4H5M6S").
// Form-state shape: scalar string (bare FLAT key, no |suffix).
function DvDurationField({ node, path, control, readOnly }: LeafProps) {
  const required = (node.min ?? 0) >= 1
  const label = nodeName(node)
  const inputId = `field-${path}`

  return (
    <Controller
      control={control}
      name={path}
      render={({ field, fieldState }) => {
        const strVal = typeof field.value === 'string' ? field.value : ''
        const err = errorMessage(fieldState.error)
        if (readOnly) return <ReadOnlyField label={label} value={strVal} />
        return (
          <div className="flex flex-col gap-1">
            <Label htmlFor={inputId}>
              {label}
              {required && <RequiredMark />}
            </Label>
            <Input
              id={inputId}
              type="text"
              placeholder="P1Y2M3DT4H5M6S"
              value={strVal}
              onChange={(e) => field.onChange(e.target.value)}
              onBlur={field.onBlur}
              aria-invalid={fieldState.invalid}
              aria-describedby={err ? `${inputId}-err` : undefined}
            />
            {err && (
              <p id={`${inputId}-err`} role="alert" className="text-destructive text-xs">
                {err}
              </p>
            )}
          </div>
        )
      }}
    />
  )
}

// DV_IDENTIFIER → plain text Input. Not in §7 main table but well-defined.
// Form-state shape: scalar string.
function DvIdentifierField({ node, path, control, readOnly }: LeafProps) {
  const required = (node.min ?? 0) >= 1
  const label = nodeName(node)
  const inputId = `field-${path}`

  return (
    <Controller
      control={control}
      name={path}
      render={({ field, fieldState }) => {
        const strVal = typeof field.value === 'string' ? field.value : ''
        const err = errorMessage(fieldState.error)
        if (readOnly) return <ReadOnlyField label={label} value={strVal} />
        return (
          <div className="flex flex-col gap-1">
            <Label htmlFor={inputId}>
              {label}
              {required && <RequiredMark />}
            </Label>
            <Input
              id={inputId}
              type="text"
              value={strVal}
              onChange={(e) => field.onChange(e.target.value)}
              onBlur={field.onBlur}
              aria-invalid={fieldState.invalid}
              aria-describedby={err ? `${inputId}-err` : undefined}
            />
            {err && (
              <p id={`${inputId}-err`} role="alert" className="text-destructive text-xs">
                {err}
              </p>
            )}
          </div>
        )
      }}
    />
  )
}

// DV_MULTIMEDIA → file input stub. §7 table row 9.
// Full MIME sniffing / ClamAV / EXIF stripping is server-side (§7.x).
// This yields a descriptor object; the server fn handles the actual upload.
function DvMultimediaField({ node, path, control, readOnly }: LeafProps) {
  const required = (node.min ?? 0) >= 1
  const label = nodeName(node)
  const inputId = `field-${path}`

  return (
    <Controller
      control={control}
      name={path}
      render={({ field, fieldState }) => {
        const err = errorMessage(fieldState.error)
        if (readOnly) {
          const descriptor = isCompositeRecord(field.value) ? field.value : undefined
          const display = typeof descriptor?.['name'] === 'string' ? descriptor['name'] : ''
          return <ReadOnlyField label={label} value={display} />
        }
        return (
          <div className="flex flex-col gap-1">
            <Label htmlFor={inputId}>
              {label}
              {required && <RequiredMark />}
            </Label>
            <Input
              id={inputId}
              type="file"
              onChange={(e) => {
                const f = e.target.files?.[0]
                if (f) {
                  field.onChange({ name: f.name, size: f.size, type: f.type })
                }
              }}
              aria-invalid={fieldState.invalid}
              aria-describedby={err ? `${inputId}-err` : undefined}
            />
            <p className="text-muted-foreground text-xs">{m.compose_multimedia_hint()}</p>
            {err && (
              <p id={`${inputId}-err`} role="alert" className="text-destructive text-xs">
                {err}
              </p>
            )}
          </div>
        )
      }}
    />
  )
}

// Fallback for unknown / unimplemented rmTypes. Renders a plain text input so
// the form remains functional. Per the §7 rule: do NOT silently invent a
// mapping for a new rmType on a production clinical surface — open an ADR.
function UnknownLeafField({ node, path, control, readOnly }: LeafProps) {
  const required = (node.min ?? 0) >= 1
  const label = nodeName(node)
  const inputId = `field-${path}`

  return (
    <Controller
      control={control}
      name={path}
      render={({ field, fieldState }) => {
        const strVal = typeof field.value === 'string' ? field.value : ''
        const err = errorMessage(fieldState.error)
        if (readOnly) return <ReadOnlyField label={label} value={strVal} />
        return (
          <div className="flex flex-col gap-1">
            <Label htmlFor={inputId}>
              {label}
              {required && <RequiredMark />}
            </Label>
            <Input
              id={inputId}
              type="text"
              value={strVal}
              onChange={(e) => field.onChange(e.target.value)}
              onBlur={field.onBlur}
              aria-invalid={fieldState.invalid}
              aria-describedby={err ? `${inputId}-err` : undefined}
            />
            {err && (
              <p id={`${inputId}-err`} role="alert" className="text-destructive text-xs">
                {err}
              </p>
            )}
          </div>
        )
      }}
    />
  )
}

// ── Leaf dispatcher ───────────────────────────────────────────────────────────

function renderLeaf(
  node: WebTemplateNode,
  path: string,
  control: Control<Record<string, unknown>>,
  readOnly?: boolean,
) {
  switch (node.rmType) {
    case 'DV_TEXT':
      return <DvTextField key={path} node={node} path={path} control={control} readOnly={readOnly} />
    case 'DV_CODED_TEXT':
      return <DvCodedTextField key={path} node={node} path={path} control={control} readOnly={readOnly} />
    case 'DV_QUANTITY':
      return <DvQuantityField key={path} node={node} path={path} control={control} readOnly={readOnly} />
    case 'DV_COUNT':
      return <DvCountField key={path} node={node} path={path} control={control} readOnly={readOnly} />
    case 'DV_BOOLEAN':
      return <DvBooleanField key={path} node={node} path={path} control={control} readOnly={readOnly} />
    case 'DV_DATE':
      return <DvDateField key={path} node={node} path={path} control={control} readOnly={readOnly} />
    case 'DV_DATE_TIME':
      return <DvDateTimeField key={path} node={node} path={path} control={control} readOnly={readOnly} />
    case 'DV_TIME':
      return <DvTimeField key={path} node={node} path={path} control={control} readOnly={readOnly} />
    case 'DV_ORDINAL':
      return <DvOrdinalField key={path} node={node} path={path} control={control} readOnly={readOnly} />
    case 'DV_PROPORTION':
      return <DvProportionField key={path} node={node} path={path} control={control} readOnly={readOnly} />
    case 'DV_DURATION':
      return <DvDurationField key={path} node={node} path={path} control={control} readOnly={readOnly} />
    case 'DV_IDENTIFIER':
      return <DvIdentifierField key={path} node={node} path={path} control={control} readOnly={readOnly} />
    case 'DV_MULTIMEDIA':
      return <DvMultimediaField key={path} node={node} path={path} control={control} readOnly={readOnly} />
    case 'DV_URI':
    case 'DV_EHR_URI':
      // URI renders as plain text; form-state shape is scalar string.
      return <DvTextField key={path} node={node} path={path} control={control} readOnly={readOnly} />
    default:
      return <UnknownLeafField key={path} node={node} path={path} control={control} readOnly={readOnly} />
  }
}

// ── ArrayFieldRenderer (inline, no circular import) ──────────────────────────
// Handles multiply-occurring nodes (max > 1 or max === -1) with useFieldArray.
// ArrayFieldRenderer calls FieldRenderer with max overridden to 1 to prevent
// infinite recursion; the outer FieldRenderer routes to this when isMulti.

interface ArrayRendererInternalProps {
  node: WebTemplateNode
  path: string
  control: Control<Record<string, unknown>>
  depth: number
  readOnly?: boolean
}

// FieldValues-typed form context used ONLY inside ArrayRendererInternal so
// that useFieldArray sees the correct type (FieldValues = Record<string, unknown>
// is structurally compatible with its `name` constraint). This is a type
// annotation on the context extraction, not a cast.
function ArrayRendererInternal({
  node,
  path,
  control,
  depth,
  readOnly,
}: ArrayRendererInternalProps) {
  // useFormContext<FieldValues> avoids the useFieldArray name-type issue:
  // FieldValues = Record<string, any>, which useFieldArray's FieldArrayPath
  // resolves to string (all keys valid).
  const formCtx = useFormContext<FieldValues>()
  const { fields, append, remove } = useFieldArray({
    control: formCtx.control,
    name: path,
  })
  // Silence the unused `control` prop lint warning — it is kept in the interface
  // for API consistency with FieldRenderer.
  void control

  const label = nodeName(node)
  const min = node.min ?? 0
  const max = node.max ?? -1
  const isUnbounded = max === -1
  const atMax = !isUnbounded && fields.length >= max
  const atMin = fields.length <= min

  const hasInputs = (node.inputs?.length ?? 0) > 0
  const newItem = hasInputs ? undefined : {}

  return (
    <Card className={cn(depth === 0 && 'border-0 shadow-none p-0')}>
      {label && (
        <CardHeader className={cn(depth === 0 && 'px-0')}>
          <CardTitle className="text-base">{label}</CardTitle>
        </CardHeader>
      )}
      <CardContent className={cn('space-y-4', depth === 0 && 'px-0')}>
        {fields.length === 0 && (
          <p className="text-muted-foreground text-sm">{m.compose_array_add()}</p>
        )}

        {fields.map((fieldItem, index) => (
          <div key={fieldItem.id} className="relative rounded-md border p-3">
            <FieldRenderer
              node={{ ...node, max: 1 }}
              path={`${path}.${index}`}
              control={control}
              depth={depth + 1}
              readOnly={readOnly}
            />
            {!readOnly && (
              <div className="mt-2 flex justify-end">
                <Button
                  type="button"
                  variant="outline"
                  size="sm"
                  disabled={atMin}
                  onClick={() => remove(index)}
                  aria-label={m.compose_array_remove({ index: String(index + 1) })}
                >
                  {m.compose_field_remove()}
                </Button>
              </div>
            )}
          </div>
        ))}

        {!readOnly && (
          <Button
            type="button"
            variant="secondary"
            size="sm"
            disabled={atMax}
            onClick={() => append(newItem)}
            aria-label={m.compose_array_add()}
          >
            {m.compose_field_add()}
          </Button>
        )}
      </CardContent>
    </Card>
  )
}

// ── FieldRenderer (exported) ─────────────────────────────────────────────────

export interface FieldRendererProps {
  node: WebTemplateNode
  /** Dot-notation path into the RHF form state. */
  path: string
  control: Control<Record<string, unknown>>
  /** Nesting depth; root = 0. Used for Card styling. */
  depth?: number
  /**
   * When true, all leaf inputs are rendered as static read-only text and
   * Add/Remove buttons are hidden. Used by CompositionViewer (§7 form pipeline).
   */
  readOnly?: boolean
}

/**
 * Recursive, rmType-aware field renderer for openEHR web templates.
 *
 * Routing logic:
 * - If max > 1 or max === -1 → ArrayRendererInternal (useFieldArray).
 * - If CONTAINER_RM_TYPES and no inputs → grouped Card/fieldset with children.
 * - Otherwise → leaf renderer dispatched by rmType.
 *
 * The form-state shape produced matches exactly what generateFormSchema builds
 * and what formStateToFlat consumes. Do not break this contract.
 *
 * When readOnly=true, leaf values render as static text; array Add/Remove
 * controls are hidden.  This mode is used by CompositionViewer.
 */
export function FieldRenderer({
  node,
  path,
  control,
  depth = 0,
  readOnly,
}: FieldRendererProps) {
  // Consume the form context to ensure RHF state is active.
  useFormContext()

  const isMulti = node.max === -1 || (node.max ?? 1) > 1
  if (isMulti) {
    return (
      <ArrayRendererInternal
        node={node}
        path={path}
        control={control}
        depth={depth}
        readOnly={readOnly}
      />
    )
  }

  if (isContainer(node)) {
    const label = nodeName(node)
    return (
      <Card className={cn(depth === 0 && 'border-0 shadow-none p-0')}>
        {label && (
          <CardHeader className={cn(depth === 0 && 'px-0')}>
            <CardTitle className="text-base">{label}</CardTitle>
          </CardHeader>
        )}
        <CardContent className={cn('space-y-4', depth === 0 && 'px-0')}>
          {(node.children ?? []).map((child) => {
            const childPath = path ? `${path}.${child.id}` : child.id
            return (
              <FieldRenderer
                key={child.id}
                node={child}
                path={childPath}
                control={control}
                depth={depth + 1}
                readOnly={readOnly}
              />
            )
          })}
        </CardContent>
      </Card>
    )
  }

  return renderLeaf(node, path, control, readOnly)
}
