// Generate typed openEHR terminology constants from the vendored terminology XML
// (ADR-0032). The openEHR terminology (codesets + id/rubric groups) is the
// authoritative internal vocabulary used by the RM (null flavours, composition
// category, setting, audit change type, …). Parsed with fast-xml-parser (a
// regen-time devDependency), offline + deterministic.
//
//   node ./scripts/term-gen.mjs           # regenerate (write)
//   node ./scripts/term-gen.mjs --check    # CI drift gate

import fs from "node:fs";
import path from "node:path";
import { XMLParser } from "fast-xml-parser";

const checkMode = process.argv.includes("--check");
const pkgDir = process.cwd();
const spec = JSON.parse(fs.readFileSync(path.join(pkgDir, "spec.json"), "utf8"));
const xml = fs.readFileSync(path.join(pkgDir, "terminology", "openehr_terminology.xml"), "utf8");

const parser = new XMLParser({
  ignoreAttributes: false,
  attributeNamePrefix: "@_",
  // always materialise these as arrays, even when a single element is present
  isArray: (name) => ["codeset", "group", "code", "concept"].includes(name),
});
const terminology = parser.parse(xml).terminology;

/** "composition category" / "MultiMedia" → { constName, typeName }. */
function names(raw, typeSuffix) {
  const words = raw.split(/[^A-Za-z0-9]+/).filter(Boolean);
  const constName = words.map((w) => w.toUpperCase()).join("_");
  const typeName = words.map((w) => w[0].toUpperCase() + w.slice(1)).join("") + typeSuffix;
  return { constName, typeName };
}

const blocks = [];

// codesets: string-valued vocabularies (no rubric).
for (const cs of terminology.codeset ?? []) {
  const { constName, typeName } = names(cs["@_openehr_id"], "Value");
  const values = (cs.code ?? []).map((c) => c["@_value"]);
  const union = values.map((v) => JSON.stringify(v)).join(" | ");
  blocks.push(
    `export type ${typeName} = ${union};\n` +
      `export const ${constName}: readonly ${typeName}[] = [${values.map((v) => JSON.stringify(v)).join(", ")}];\n`,
  );
}

// groups: code → rubric maps.
for (const g of terminology.group ?? []) {
  const { constName, typeName } = names(g["@_name"], "Code");
  const concepts = (g.concept ?? []).map((c) => ({ id: String(c["@_id"]), rubric: String(c["@_rubric"]) }));
  const union = concepts.map((c) => JSON.stringify(c.id)).join(" | ");
  const entries = concepts.map((c) => `  ${JSON.stringify(c.id)}: ${JSON.stringify(c.rubric)},`).join("\n");
  blocks.push(
    `export type ${typeName} = ${union};\n` +
      `export const ${constName}: Record<${typeName}, string> = {\n${entries}\n};\n`,
  );
}

const body =
  `// AUTOGENERATED — do not edit by hand. Run \`pnpm regen\`.\n` +
  `// Source: ${spec.schemaSource} ${spec.schemaRef} @ ${spec.schemaCommit}\n` +
  `// openEHR ${spec.component} ${spec.specVersion} terminology (codesets + groups). See ADR-0032.\n` +
  `/* eslint-disable */\n\n` +
  blocks.join("\n");

const genFile = path.join(pkgDir, "src", "generated", "index.ts");
if (checkMode) {
  const existing = fs.existsSync(genFile) ? fs.readFileSync(genFile, "utf8") : "";
  if (existing !== body) {
    console.error("[term-gen] DRIFT: generated terminology differs from committed. Run `pnpm regen`.");
    process.exit(1);
  }
  console.log(`[term-gen] TERM ${spec.specVersion} up to date.`);
} else {
  fs.mkdirSync(path.dirname(genFile), { recursive: true });
  fs.writeFileSync(genFile, body);
  console.log(`[term-gen] wrote terminology constants → src/generated/index.ts`);
}
